#!/usr/bin/env node
/**
 * tools/build-data-js.mjs — 把 data/words-core.json 编译成 miniprogram 可 require 的 .js
 *
 * 输出: miniprogram/data/words-core.js
 *       module.exports = { meta: {...}, words: [...] }
 *
 * 这样微信小程序可以直接 require('../data/words-core.js')，避免读文件系统。
 * 注意：895KB 进主包（实际 gzip ~300KB），阶段三再考虑分包。
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'data', 'words-core.json');
const OUT_DIR = path.join(ROOT, 'miniprogram', 'data');
const OUT = path.join(OUT_DIR, 'words-core.js');

if (!fs.existsSync(SRC)) {
  console.error(`[build-data-js] missing source: ${SRC}`);
  process.exit(1);
}

const raw = fs.readFileSync(SRC, 'utf8');
const data = JSON.parse(raw);
const words = data.words;
const meta = data.meta;

if (!Array.isArray(words) || words.length === 0) {
  console.error('[build-data-js] empty words array');
  process.exit(1);
}

// 输出 module.exports
const header = `// auto-generated by tools/build-data-js.mjs — do not edit
// source: data/words-core.json (${raw.length} bytes, ${words.length} words, v${meta.version})
// license: ${meta.source_license} (${meta.source_url})
// attribution: ${meta.attribution}

module.exports = `;
const footer = `;\n`;

const body = JSON.stringify(data, null, 0);  // 单行无空格省字节

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, header + body + footer, 'utf8');

const outSize = fs.statSync(OUT).size;
console.log(`[build-data-js] ${words.length} words -> ${OUT}`);
console.log(`[build-data-js] raw=${raw.length}  js=${outSize}  delta=+${outSize - raw.length} (+${((outSize - raw.length) / raw.length * 100).toFixed(1)}%)`);
